MODEL:
  META_ARCHITECTURE: "CenterNet"
  WEIGHTS: ""
  BACKBONE:
    NAME: "build_hourglass_net"
    FREEZE_AT: 100
    FREEZE_ALL: False
  SIZE_DIVISIBILITY: 64
  HOURGLASS:
    OUT_FEATURES: ["hg_stack_0"]
    NUM_STACKS: 1
    NUM_BLOCKS: 5
    NUM_FEATURES: 256
    NORM: "SyncBN"
  NECKS:
    ENABLED: False
  HEADS:
    NAME: CenternetRelationHeads
    IN_FEATURES: ["hg_stack_0"]
    CONV_DIM: 128
    NUM_CONV: 4
    NUM_STAGES: 1
    NORM: "SyncBN"
    FREEZE: []
    RAF:
      DILATION: 1
      LAST_DEFORM_ON: True
    NUM_CLASSES: 150
    LOSS:
      HEATMAP_LOSS_TYPE: "efficient_focal_loss"
      WH_WEIGHT: 0.1
      RAF_WEIGHT: 1.0
DATASETS:
  TRAIN: ("vg_train",)
#  VAL: ("vg_val",)
  TEST: ("vg_train",)
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 5.0
  IMS_PER_BATCH: 2
  BASE_LR: 0.01
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 100
  STEPS: ()
  MAX_ITER: 500
  CHECKPOINT_PERIOD: 500
INPUT:
  MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
  ADD_IGNORE: True
RELATION:
  RELATION_ON: True
  USE_GT_BOX: False
  USE_GT_OBJECT_LABEL: False
OUTPUT_DIR: "./output/vg/quick_schedules/fcsgg_hourglass_single_256x512_ms"
SEED: 2020
VERSION: 2
