MODEL:
  META_ARCHITECTURE: "CenterNet"
  WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
    FREEZE_AT: 2
    FREEZE_ALL: False
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "FrozenBN" # "SyncBN" "FrozenBN"
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  NECKS:
    ENABLED: True
    NAME: FPNUpSampleNeck
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NORM: "SyncBN"
    FREEZE: False
  HEADS:
    NAME: CenternetMultiStageHeads
    CONV_DIM: 256
    NUM_CONV: 2
    NUM_STAGES: 2
    NORM: "SyncBN"
    FREEZE: []
    RAF:
      DILATION: 2
      LAST_DEFORM_ON: True
    NUM_CLASSES: 150
    IN_FEATURES: ["fpn_fused"]
    LOSS:
      HEATMAP_LOSS_TYPE: "efficient_focal_loss"
      WH_WEIGHT: 0.1
      RAF_WEIGHT: 0.1
DATASETS:
  TRAIN: ("vg_train",)
#  VAL: ("vg_val",)
  TEST: ("vg_train",)
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 5.0
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
  WARMUP_FACTOR: 0.005
  WARMUP_ITERS: 200
  STEPS: ()
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 500
INPUT:
  MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
RELATION:
  RELATION_ON: True
  USE_GT_BOX: False
  USE_GT_OBJECT_LABEL: False
OUTPUT_DIR: "./output/vg/quick_schedules/fcsgg_res50fpn_fpnupsample_multistage_deform_256x512_ms"
SEED: 2020
VERSION: 2
