_BASE_: "../FCSGG-HRNet-multistage-deform-256x512-ms.yaml"
MODEL:
  HEADS:
    NAME: CenternetMultiStageHeads
    NUM_STAGES: 2
    NUM_CONV: 4
    NORM: "SyncBN"
    RAF:
      LAST_DEFORM_ON: True
      DILATION: 1
DATASETS:
  TRAIN: ("vg_train",)
#  VAL: ("vg_val",)
  TEST: ("vg_train",)
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  CLIP_GRADIENTS:
    ENABLED: True
  IMS_PER_BATCH: 2
  BASE_LR: 0.002
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 100
  STEPS: ()
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 500
INPUT:
  MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
RELATION:
  RELATION_ON: True
OUTPUT_DIR: "./output/vg/quick_schedules/fcsgg_hrnet32_multistage_deform_256x512_ms"
SEED: 2020
VERSION: 2
