_BASE_: "Quick-FCSGG-Base.yaml"
MODEL:
  META_ARCHITECTURE: "CenterNet"
  WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"
  BACKBONE:
    NAME: "build_resnet_bifpn_backbone"
    FREEZE_AT: -1
    FREEZE_ALL: False
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    REPEAT: 1
    NORM: SyncBN
    NUM_BRANCHES: 1
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "SyncBN" # "SyncBN" "FrozenBN"
    DEPTH: 50
  HEADS:
    NAME: MultiScaleSwitchNormAttnHeads
    SHARED: True
    CONV_DIM: 64
    NUM_CONV: 4
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 150
    NORM: "SyncBN"
    OUTPUT_STRIDES: [4, 8, 16, 32]
    FREEZE: []#["cls_head", "wh_head", "reg_head", "raf_head"]
    RAF:
      KERNEL_SIZE: 3
      DILATION: 1
      CONV_DIM: 64
      NUM_CONV: 4
      LAST_DEFORM_ON: False
      NON_LOCAL: False
      CLASS_BALANCE: False
RELATION:
  RELATION_ON: True
  USE_GT_BOX: False
  USE_GT_OBJECT_LABEL: False
INPUT:
  FLIP: FALSE
  CROP:
    ENABLED: False
    SIZE: [0.8, 0.8]
  CENTER_GAUSSIAN_IOU_MIN_OVERLAPS: [0.5, 0.7, 0.9, 1.0]
  GT_SCALE_AWARE: True
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 100
  STEPS: (500,)
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 500
