_BASE_: "Quick-FCSGG-Base.yaml"
MODEL:
  META_ARCHITECTURE: "CenterNet"
  WEIGHTS: ""
  BACKBONE:
    NAME: "build_dual_decoder_hourglass_net"
    FREEZE_AT: -1
    FREEZE_ALL: False
  SIZE_DIVISIBILITY: 64
  HOURGLASS:
    OUT_FEATURES: ["hg_stack_1", "hg_stack_2"]
    NUM_STACKS: 3
    NUM_BLOCKS: [4, 2, 2]
    NUM_FEATURES: 256
    NORM: "SyncBN"
  NECKS:
    ENABLED: False
  HEADS:
    NAME: DualDecoderHeads
    IN_FEATURES: ["hg_stack_1", "hg_stack_2"]
    CONV_DIM: 128
    NUM_CONV: 1
    NORM: "SyncBN"
    FREEZE: []
    OUTPUT_STRIDES: [4]
    RAF:
      DILATION: 1
      LAST_DEFORM_ON: False
    NUM_CLASSES: 150
DATASETS:
  TRAIN: ("vg_train",)
#  VAL: ("vg_val",)
  TEST: ("vg_train",)
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 5.0
  IMS_PER_BATCH: 4
  BASE_LR: 0.01
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 100
  STEPS: (500,)
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 500
INPUT:
  MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
  CENTER_GAUSSIAN_IOU_MIN_OVERLAPS: [0.7]
  GT_SCALE_AWARE: False
RELATION:
  RELATION_ON: True
  USE_GT_BOX: False
  USE_GT_OBJECT_LABEL: False
