_BASE_: "Quick-FCSGG-Base.yaml"
MODEL:
  SIZE_DIVISIBILITY: 64
  META_ARCHITECTURE: "CenterNet"
  WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
    FREEZE_AT: -1
    FREEZE_ALL: False
  FPN:
    IN_FEATURES: [ "res2", "res3", "res4", "res5" ]
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: [ "res2", "res3", "res4", "res5" ]
    NORM: "SyncBN" # "SyncBN" "FrozenBN"
  HEADS:
    NAME: MultiScaleHeads
    CONV_DIM: 64
    NUM_CONV: 4
    NORM: "GN"
    IN_FEATURES: [ "p2", "p3", "p4", "p5" ]
    OUTPUT_STRIDES: [ 4, 8, 16, 32 ]
    RAF:
      DOWN_SAMPLE_RATIO: 1
      CONV_DIM: 64
      CONV_DIMS: [64, 64, 64, 64]
      NUM_CONV: 4
      LOSS_TYPE: ("l2", "all", "normal", 1)
INPUT:
  GT_SCALE_AWARE: True
  CENTER_GAUSSIAN_IOU_MIN_OVERLAPS: [0.5, 0.5, 0.5, 0.5]
RELATION:
  RELATION_ON: True
  USE_GT_BOX: False
  USE_GT_OBJECT_LABEL: False
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 100
  STEPS: (500,)
  MAX_ITER: 2000
  CHECKPOINT_PERIOD: 500
#DATASETS:
#  TEST: ("vg_minitest",)

