_BASE_: "Quick-FCSGG-Base.yaml"
MODEL:
  META_ARCHITECTURE: "CenterNet"
  WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"
  SIZE_DIVISIBILITY: 32
  BACKBONE:
    NAME: "build_resnet_bifpn_backbone"
    FREEZE_AT: 2
    FREEZE_ALL: False
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: ""
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "SyncBN" # "SyncBN" "FrozenBN"
  HEADS:
    NAME: MultiScaleHeads
    CONV_DIM: 64
    NUM_CONV: 4
    SHARED: True
    IN_FEATURES: ["p2", "p3", "p4", "p5"] # ,
    NUM_CLASSES: 150
    NORM: "GN"
    OUTPUT_STRIDES: [4, 8, 16, 32]
    RAF:
      KERNEL_SIZE: 3
      DILATION: 1
      LAST_DEFORM_ON: False
INPUT:
  MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
  ADD_IGNORE: False
  CENTER_GAUSSIAN_IOU_MIN_OVERLAPS: [0.5, 0.7, 0.9, 1.0]
  GT_SCALE_AWARE: True
  CROP:
    ENABLED: False
    SIZE: [0.8, 0.8]
RELATION:
  RELATION_ON: True
  USE_GT_BOX: False
  USE_GT_OBJECT_LABEL: False

