_BASE_: "Quick-FCSGG-Base.yaml"
MODEL:
  SIZE_DIVISIBILITY: 128
  PIXEL_STD: [57.375, 57.120, 58.395]
  META_ARCHITECTURE: "CenterNet"
  WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x/139173657/model_final_68b088.pkl"
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_backbone"
    FREEZE_AT: 2
    FREEZE_ALL: False
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
    NORM: "SyncBN" # "SyncBN" "FrozenBN"
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
  HEADS:
    NAME: MultiScaleSwitchNormHeads
    CONV_DIM: 256
    NUM_CONV: 4
    NORM: "SyncBN"
    IN_FEATURES: ["p3", "p4", "p5", "p6", "p7"]
    OUTPUT_STRIDES: [8, 16, 32, 64, 128]
    LOSS:
      WH_WEIGHT: 0.1
    RAF:
      DOWN_SAMPLE_RATIO: 1
      CONV_DIM: 512
      NUM_CONV: 4
      SPLIT: True
      LOSS_TYPE: ("l2", "all", "normal", 1)
INPUT:
  GT_SCALE_AWARE: True
  CENTER_GAUSSIAN_IOU_MIN_OVERLAPS: [0.5, 0.5, 0.5, 0.5, 0.5]
  MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 640
RELATION:
  RELATION_ON: True
  USE_GT_BOX: False
  USE_GT_OBJECT_LABEL: False
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.001 # linear scale these
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 100
  STEPS: (500, ) # linear scale these
  MAX_ITER: 1000 # linear scale these

