_BASE_: "Quick-FCSGG-Base.yaml"
MODEL:
  META_ARCHITECTURE: "CenterNet"
  WEIGHTS: "detectron2://Misc/mask_rcnn_R_50_FPN_3x_dconv_c3-c5/144998336/model_final_821d0b.pkl"
  BACKBONE:
    NAME: "build_resnet_dual_bifpn_backbone"
    FREEZE_AT: -1
    FREEZE_ALL: False
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    REPEAT: 1
    NORM: SyncBN
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "SyncBN" # "SyncBN" "FrozenBN"
    DEFORM_ON_PER_STAGE: [False, True, True, True] # on Res3,Res4,Res5
    DEFORM_MODULATED: False
  HEADS:
    NAME: MultiScaleSwitchNormDualHeads
    SHARED: True
    CONV_DIM: 64
    NUM_CONV: 4
    IN_FEATURES: ["p2_0", "p3_0", "p4_0", "p5_0", "p2_1", "p3_1", "p4_1", "p5_1"]
    NUM_CLASSES: 150
    NORM: "SyncBN"
    OUTPUT_STRIDES: [4, 8, 16, 32]
    FREEZE: []#["cls_head", "wh_head", "reg_head", "raf_head"]
    RAF:
      KERNEL_SIZE: 3
      DILATION: 1
      LAST_DEFORM_ON: False
    LOSS:
      WH_WEIGHT: 1.0
INPUT:
  CROP:
    ENABLED: False
    SIZE: [0.8, 0.8]
  CENTER_GAUSSIAN_IOU_MIN_OVERLAPS: [0.5, 0.7, 0.9, 1.0]

