_BASE_: "Quick-FCSGG-Base.yaml"
MODEL:
  META_ARCHITECTURE: "CenterNet"
  WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"
  BACKBONE:
    NAME: "build_resnet_fpn_p2_backbone"
    FREEZE_AT: 2
    FREEZE_ALL: False
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "FrozenBN" # "SyncBN" "FrozenBN"
  HEADS:
    NAME: CenternetRelationHeads
    IN_FEATURES: ["p2"]
    NUM_CLASSES: 150

#OUTPUT_DIR: "./output/vg/fcsgg_res50_fpn_p2_608x1024"

