_BASE_: "Quick-FCSGG-Base.yaml"
MODEL:
  META_ARCHITECTURE: "CenterNet"
  WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"
  SIZE_DIVISIBILITY: 128
  BACKBONE:
    NAME: "build_resnet_bifpn_backbone"
    FREEZE_AT: 2
    FREEZE_ALL: False
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
    REPEAT: 3
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "FrozenBN" # "SyncBN" "FrozenBN"
  HEADS:
    NAME: MultiScaleHeads
    CONV_DIM: 64
    SHARED: True
    IN_FEATURES: ["p3", "p4", "p5", "p6", "p7"] # ,
    NUM_CLASSES: 150
    NORM: "GN"
    OUTPUT_STRIDES: [8, 16, 32, 64, 128]
    RAF:
      KERNEL_SIZE: 3
      DILATION: 1
      LAST_DEFORM_ON: True
RELATION:
  RELATION_ON: True
  USE_GT_BOX: False
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.004
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 100
  STEPS: ()
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 500
OUTPUT_DIR: "./output/vg/quick_schedules/shared_head"

