MODEL:
  META_ARCHITECTURE: "CenterNet"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE:
    NAME: "build_resnet_backbone"
  RESNETS:
    DEPTH: 50
#    RES2_OUT_CHANNELS: 64 # must set 64 for R18/34
    OUT_FEATURES: ["res5"]
  HEADS:
    NUM_CLASSES: 1 # balloon toy example
DATASETS:
  TRAIN: ("balloon_train",)
  TEST: ("balloon_val",)
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.0001
  WARMUP_FACTOR: 0.002
  WARMUP_ITERS: 0
  STEPS: (1000, 3000)
  MAX_ITER: 5000
  CHECKPOINT_PERIOD: 1000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
OUTPUT_DIR: "./output/balloon"
SEED: 2020
VERSION: 2
