MODEL:
  META_ARCHITECTURE: "CenterNet"
  WEIGHTS: ""
  BACKBONE:
    NAME: "build_hourglass_net"
    FREEZE_AT: -1
  SIZE_DIVISIBILITY: 64
  NECKS:
    ENABLED: False
  HEADS:
    NAME: CenternetHeads
    NUM_CLASSES: 150
    IN_FEATURES: ["hg_stage_7"]
    LOSS:
      HEATMAP_LOSS_TYPE: "efficient_focal_loss"
      WH_WEIGHT: 0.1
DATASETS:
  TRAIN: ("vg_train",)
#  VAL: ("vg_val",)
  TEST: ("vg_test",)
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  WARMUP_FACTOR: 0.002
  WARMUP_ITERS: 500
  STEPS: (40000, 70000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 5000
INPUT:
  MIN_SIZE_TRAIN: (256, 320, 384, 448, 512) #(640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 256
  MAX_SIZE_TEST: 512
OUTPUT_DIR: "./output/vg/hourglass_256x512_ms"
SEED: 2020
VERSION: 2
