MODEL:
  META_ARCHITECTURE: "CenterNet"
  BACKBONE:
    NAME: "build_dla_backbone"
    FREEZE_AT: -1
    WEIGHTS: "https://drive.google.com/uc?export=download&id=1pl_-ael8wERdUREEnaIfqOV_VF2bEVRT"
  DLA:
    WEIGHTS: "http://dl.yf.io/dla/models/imagenet/dla34-ba72cf86.pth"
    CONV_BODY: "DLA34"
    FREEZE: False
    NORM: "SyncBN"
  NECKS:
    ENABLED: True
    NAME: DLAUpSampleNeck
    IN_FEATURES: ["level2", "level3", "level4", "level5"]
  HEADS:
    NUM_CLASSES: 150
    IN_FEATURES: ["dla_fused"]
    LOSS:
      HEATMAP_LOSS_TYPE: "efficient_focal_loss"
DATASETS:
  TRAIN: ("vg_train",)
#  VAL: ("vg_val",)
  TEST: ("vg_test",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.002
  WARMUP_FACTOR: 0.002
  WARMUP_ITERS: 0
  STEPS: (60000, 100000)
  MAX_ITER: 120000
  CHECKPOINT_PERIOD: 5000
INPUT:
  MIN_SIZE_TRAIN: (600,) #(640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1000
OUTPUT_DIR: "./output/vg/dla34-120000"
SEED: 2020
VERSION: 2
