_BASE_: "FCSGG-Base.yaml"
MODEL:
  SIZE_DIVISIBILITY: 64
  PIXEL_STD: [57.375, 57.120, 58.395]
  META_ARCHITECTURE: "CenterNet"
  WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x/139173657/model_final_68b088.pkl"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
    FREEZE_AT: -1
    FREEZE_ALL: False
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "SyncBN" # "SyncBN" "FrozenBN"
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
  HEADS:
    NAME: MultiScaleSwitchNormHeads
    CONV_DIM: 256
    NUM_CONV: 4
    NORM: "SyncBN"
    IN_FEATURES: [ "p2", "p3", "p4", "p5" ]
    OUTPUT_STRIDES: [ 4, 8, 16, 32 ]
    LOSS:
      WH_WEIGHT: 0.1
    RAF:
      DOWN_SAMPLE_RATIO: 1
      CONV_DIM: 256
      NUM_CONV: 4
INPUT:
  GT_SCALE_AWARE: True
  CENTER_GAUSSIAN_IOU_MIN_OVERLAPS: [0.5, 0.5, 0.5, 0.5]
RELATION:
  RELATION_ON: True
  USE_GT_BOX: False
  USE_GT_OBJECT_LABEL: False
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.002 # linear scale these
  WARMUP_FACTOR: 0.002
  WARMUP_ITERS: 500
  STEPS: (120000, 160000) # linear scale these
  MAX_ITER: 180000 # linear scale these

OUTPUT_DIR: "./output/vg/fcsgg_resx101_32x8d_fpn_512x512"

