MODEL:
  META_ARCHITECTURE: "CenterNet"
  RELATION_ON: False
  WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
    FREEZE_AT: -1
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "SyncBN" # "SyncBN" "FrozenBN"
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  NECKS:
    ENABLED: True
    NAME: FPNUpSampleNeck
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NORM: "SyncBN"
  HEADS:
    NAME: CenternetRelationHeads
    NUM_CLASSES: 150
    IN_FEATURES: ["fpn_fused"]
    LOSS:
      HEATMAP_LOSS_TYPE: "efficient_focal_loss"
      WH_WEIGHT: 0.1
DATASETS:
  TRAIN: ("vg_train",)
#  VAL: ("vg_val",)
  TEST: ("vg_test",)
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  CLIP_GRADIENTS:
    ENABLED: True
  IMS_PER_BATCH: 32
  BASE_LR: 0.0004
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 100
  STEPS: (40000, 70000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 5000
INPUT:
  LOAD_RELATIONS: True
  MIN_SIZE_TRAIN: (256, 320, 384, 448, 512)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 256
  MAX_SIZE_TEST: 512
OUTPUT_DIR: "./output/vg/fcsgg_res50fpn_nofreeze_fpnupsample_256x512_ms"
SEED: 2020
VERSION: 2
