_BASE_: "FCSGG-Base.yaml"
MODEL:
  META_ARCHITECTURE: "CenterNet"
  HRNET:
    WEIGHTS: "output/FasterR-CNN-HR48-2x.pth"
    FINAL_STAGE_MULTISCALE: True
    NORM: "SyncBN"
    STAGE2:
      NUM_CHANNELS: [48, 96]
    STAGE3:
      NUM_CHANNELS: [48, 96, 192]
    STAGE4:
      NUM_CHANNELS: [48, 96, 192, 384]
  BACKBONE:
    NAME: "build_hrnet_backbone"
#    FREEZE_ALL: True
  NECKS:
    ENABLED: True
    NAME: ConcatNeck
    UPSAMPLE_MODE: "bilinear"
    IN_FEATURES: [ "hr2", "hr3", "hr4", "hr5" ]
  HEADS:
    NAME: CenternetRelationHeads
    CONV_DIM: 256
    NUM_CONV: 4
    NORM: "SyncBN"
    IN_FEATURES: [ "cat" ]
    OUTPUT_STRIDES: [ 4 ]
#    FREEZE: ["cls_head", "wh_head", "reg_head"]
    LOSS:
      WH_WEIGHT: 0.1
      RAF_WEIGHT: 0.1
    RAF:
      DOWN_SAMPLE_RATIO: 1
      CONV_DIM: 256
      NUM_CONV: 7
      SPLIT: True
      ADD_COORD: True
      LOSS_TYPE: ("l1", "pos", "normal", 1.0)
RELATION:
  RELATION_ON: True
  USE_GT_BOX: False
  USE_GT_OBJECT_LABEL: False
INPUT:
  GT_SCALE_AWARE: False
  CENTER_GAUSSIAN_IOU_MIN_OVERLAPS: [0.5]
SOLVER:
  IMS_PER_BATCH: 48 # linear scale these
  BASE_LR: 0.002 # linear scale these
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  STEPS: (40000, 80000) # linear scale these
  MAX_ITER: 90000 # linear scale these
DATASETS:
  TEST: ("vg_minitest",)
OUTPUT_DIR: "./output/vg/fcsgg_hrnet_w48_coordconv_512x512_ms"