_BASE_: "FCSGG-Base.yaml"
MODEL:
  META_ARCHITECTURE: "CenterNet"
  HRNET:
    WEIGHTS: "output/FasterR-CNN-HR32-3x.pth"
    FINAL_STAGE_MULTISCALE: True
    NORM: "SyncBN"
    UPSAMPLE_MODE: "bilinear"
  BACKBONE:
    NAME: "build_hrnet_backbone"
    FREEZE_ALL: False
  NECKS:
    ENABLED: True
    NAME: ConcatNeck
    UPSAMPLE_MODE: "bilinear"
    IN_FEATURES: ["hr2", "hr3", "hr4", "hr5"]
  HEADS:
    NAME: CenternetRelationHeads
    CONV_DIM: 256
    NUM_CONV: 4
    NORM: "SyncBN"
    IN_FEATURES: ["cat"]
    OUTPUT_STRIDES: [4]
    LOSS:
      WH_WEIGHT: 0.1
    RAF:
      DOWN_SAMPLE_RATIO: 2
      CONV_DIM: 512
      CONV_DIMS: [512, 512, 512, 512]
      NUM_CONV: 4
      LOSS_TYPE: ("l1", "pos", "normal", 1)
RELATION:
  RELATION_ON: True
  USE_GT_BOX: False
  USE_GT_OBJECT_LABEL: False
INPUT:
  GT_SCALE_AWARE: False
  CENTER_GAUSSIAN_IOU_MIN_OVERLAPS: [0.5]
SOLVER:
  IMS_PER_BATCH: 48 # linear scale these
  BASE_LR: 0.002 # linear scale these
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 100
  STEPS: (60000, 90000) #(40000, 80000) # linear scale these
  MAX_ITER: 120000 # linear scale these
  CHECKPOINT_PERIOD: 5000
#DATASETS:
#  TEST: ("vg_minitest",)
OUTPUT_DIR: "./output/vg/fcsgg_hrnet_w32_2xdownraf_512x512_ms"
