_BASE_: "FCSGG-Base.yaml"
MODEL:
  SIZE_DIVISIBILITY: 64
  META_ARCHITECTURE: "CenterNet"
  HRNET:
    WEIGHTS: "output/FasterR-CNN-HR32-3x.pth"
    FINAL_STAGE_MULTISCALE: True
    NORM: "SyncBN"
    UPSAMPLE_MODE: "bilinear"
  BACKBONE:
    NAME: "build_hrnet_backbone"
  NECKS:
    ENABLED: True
    NAME: HRFPN
    IN_FEATURES: [ "hr2", "hr3", "hr4", "hr5" ]
    OUT_CHANNELS: [ 256 ]
    UPSAMPLE_MODE: "bilinear"
    NORM: "SyncBN"
  HEADS:
    NAME: MultiScaleSwitchNormHeads
    CONV_DIM: 128
    NUM_CONV: 4
    NORM: "SyncBN"
    IN_FEATURES: [ "p2", "p3", "p4", "p5" ]
    OUTPUT_STRIDES: [ 4, 8, 16, 32 ]
    LOSS:
      WH_WEIGHT: 0.1
    RAF:
      DOWN_SAMPLE_RATIO: 1
      LAST_DEFORM_ON: True
      CONV_DIM: 256
      NUM_CONV: 4
RELATION:
  RELATION_ON: True
INPUT:
  GT_SCALE_AWARE: True
  GT_REGRESSION_SCALE_AWARE: False
  CENTER_GAUSSIAN_IOU_MIN_OVERLAPS: [0.5, 0.5, 0.5, 0.5]
  MIN_SIZE_TRAIN: (512, 576, 640, 704, 768, 832)
  MAX_SIZE_TRAIN: 832
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 832
SOLVER:
  IMS_PER_BATCH: 24
  BASE_LR: 0.0004 # linear scale these
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 100
  STEPS: (40000, 80000) # linear scale these
  MAX_ITER: 90000 # linear scale these
OUTPUT_DIR: "./output/vg/fcsgg_hrnet_w32_hrfpn_640x1024_ms"
