_BASE_: "FCSGG-Base.yaml"
MODEL:
  SIZE_DIVISIBILITY: 64
  META_ARCHITECTURE: "CenterNet"
  HRNET:
    WEIGHTS: "output/FasterR-CNN-HR48-2x.pth"
    FINAL_STAGE_MULTISCALE: True
    NORM: "SyncBN"
    UPSAMPLE_MODE: "bilinear"
    STAGE2:
      NUM_CHANNELS: [ 48, 96 ]
    STAGE3:
      NUM_CHANNELS: [ 48, 96, 192 ]
    STAGE4:
      NUM_CHANNELS: [ 48, 96, 192, 384 ]
  BACKBONE:
    NAME: "build_hrnet_backbone"
    FREEZE_ALL: False
  NECKS:
    ENABLED: True
    NAME: HRFPN
    IN_FEATURES: [ "hr2", "hr3", "hr4", "hr5" ]
    OUT_CHANNELS: [ 256 ]
    UPSAMPLE_MODE: "bilinear"
    NORM: "SyncBN"
  HEADS:
#    FREEZE: ["cls_head", "wh_head", "reg_head"]
    NAME: MultiScaleSwitchNormHeads
    CONV_DIM: 256
    NUM_CONV: 4
    BN_MOMENTUM: 0.1
    NORM: "SyncBN"
    IN_FEATURES: [ "p2", "p3", "p4", "p5" ]
    OUTPUT_STRIDES: [ 4, 8, 16, 32 ]
    LOSS:
      WH_WEIGHT: 0.1
    RAF:
      DOWN_SAMPLE_RATIO: 2
      CONV_DIM: 512
      NUM_CONV: 4
RELATION:
  RELATION_ON: True
INPUT:
  GT_SCALE_AWARE: False
  GT_REGRESSION_SCALE_AWARE: True
  CENTER_GAUSSIAN_IOU_MIN_OVERLAPS: [0.5, 0.6, 0.7, 0.8]
SOLVER:
  IMS_PER_BATCH: 8 # linear scale these
  BASE_LR: 0.0002 # linear scale these
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 100
  STEPS: (20000, 60000) #(40000, 80000) # linear scale these
  MAX_ITER: 90000 # linear scale these
DATASETS:
  TEST: ("vg_minitest",)
OUTPUT_DIR: "./output/vg/fcsgg_hrnet_w48_hrfpn_512x512_ms_no_reg"
