_BASE_: "FCSGG-Base.yaml"
MODEL:
  PIXEL_STD: [57.375, 57.120, 58.395]
  META_ARCHITECTURE: "CenterNet"
  WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x/139173657/model_final_68b088.pkl"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
    FREEZE_AT: 2
    FREEZE_ALL: False
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
    NORM: "FrozenBN" # "SyncBN" "FrozenBN"
  HEADS:
    NAME: MultiScaleHeads
    SHARED: True
    IN_FEATURES: ["p2", "p3", "p4", "p5"] # ,
    NUM_CLASSES: 150
    NORM: "GN"
    OUTPUT_STRIDES: [4, 8, 16, 32]
    RAF:
      KERNEL_SIZE: 3
      DILATION: 1
      LAST_DEFORM_ON: False
INPUT:
  CROP:
    ENABLED: False
    SIZE: [0.8, 0.8]
  MIN_SIZE_TRAIN: (256, 320, 384, 448, 512)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
  ADD_IGNORE: False
  CENTER_GAUSSIAN_IOU_MIN_OVERLAPS: [0.5, 0.7, 0.9, 1.0]

RELATION:
  RELATION_ON: True
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.002
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 0
  STEPS: (80000, 120000)
  MAX_ITER: 160000
  CHECKPOINT_PERIOD: 5000
OUTPUT_DIR: "./output/vg/fcsgg_resx101_32x8d_fpn_multiscalehead_ms"

