_BASE_: "FCSGG-Base.yaml"
MODEL:
  META_ARCHITECTURE: "CenterNet"
  WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"
  BACKBONE:
    NAME: "build_resnet_fpn_p2_backbone"
    FREEZE_AT: -1
    FREEZE_ALL: False
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "SyncBN" # "SyncBN" "FrozenBN"
  HEADS:
    NAME: CenternetRelationHeads
    IN_FEATURES: ["p2"]
    NUM_CLASSES: 150
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.0002 # start from 0.02
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 0
  STEPS: (30000, 60000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 5000
OUTPUT_DIR: "./output/vg/fcsgg_res50_fpn_p2_ms"

