_BASE_: "FCSGG-Base.yaml"
MODEL:
  META_ARCHITECTURE: "CenterNet"
  WEIGHTS: ""
  BACKBONE:
    NAME: "build_triad_net"
    FREEZE_AT: -1
    FREEZE_ALL: False
  SIZE_DIVISIBILITY: 64
  TRIAD:
    OUT_FEATURES: ["decoder_0", "decoder_1"]
    NUM_BRANCHES: 2
    ENCODER_BLOCKS: 2
    DECODER_BLOCKS: [2, 2]
    NUM_FEATURES: 256
    NORM: "SyncBN"
  NECKS:
    ENABLED: False
  HEADS:
    NAME: DualDecoderHeads
    IN_FEATURES: ["decoder_0", "decoder_1"]
    CONV_DIM: 256
    NUM_CONV: 2
    NORM: "SyncBN"
    FREEZE: []
    OUTPUT_STRIDES: [4]
    RAF:
      DILATION: 1
      LAST_DEFORM_ON: False
      CLASS_BALANCE: False
    NUM_CLASSES: 150
SOLVER:
  IMS_PER_BATCH: 48
  BASE_LR: 0.01
  WARMUP_FACTOR: 0.005
  WARMUP_ITERS: 200
  STEPS: (40000, 80000) # linear scale these (20000,
  MAX_ITER: 120000 # linear scale these
INPUT:
  ADD_IGNORE: False
  CENTER_GAUSSIAN_IOU_MIN_OVERLAPS: [0.5]
  GT_SCALE_AWARE: False
  CROP:
    ENABLED: False
    SIZE: [ 0.8, 0.8 ]
  MIN_SIZE_TRAIN: (512,)
RELATION:
  RELATION_ON: True
  USE_GT_BOX: False
  USE_GT_OBJECT_LABEL: False
DATASETS:
#  TRAIN: ("vg_debug",)
  TEST: ("vg_minitest",)
OUTPUT_DIR: "./output/vg/fcsgg_triadnet_512x512_ms"