_BASE_: "FCSGG-Base.yaml"
MODEL:
  SIZE_DIVISIBILITY: 128
  META_ARCHITECTURE: "CenterNet"
  HRNET:
    WEIGHTS: "output/FasterR-CNN-HR48-2x.pth"
    FINAL_STAGE_MULTISCALE: True
    NORM: "SyncBN"
    UPSAMPLE_MODE: "bilinear"
    STAGE2:
      NUM_CHANNELS: [ 48, 96 ]
    STAGE3:
      NUM_CHANNELS: [ 48, 96, 192 ]
    STAGE4:
      NUM_CHANNELS: [ 48, 96, 192, 384 ]

  BACKBONE:
    NAME: "build_hrnet_backbone"
    FREEZE_ALL: False
  FPN:
    NUM_BRANCHES: 2
  NECKS:
    ENABLED: True
    NAME: TridentNeck
    IN_FEATURES: [ "hr2", "hr3", "hr4", "hr5" ]
    OUT_CHANNELS: [ 256 ]
    UPSAMPLE_MODE: "bilinear"
    NORM: "SyncBN"
    OUT_STRIDES: [8, 8, 8]
    TRIDENT:
      BOTTLENECK_CHANNELS: 256
      BLOCK_OUT_CHANNELS: 512
  HEADS:
#    FREEZE: ["cls_head", "wh_head", "reg_head"]
    NAME: MultiScaleHeads
    CONV_DIM: 256
    NUM_CONV: 2
    BN_MOMENTUM: 0.01
    NORM: "GN"
    IN_FEATURES: ["d1", "d2", "d3"]
    OUTPUT_STRIDES: [8, 8, 8]
    LOSS:
      WH_WEIGHT: 0.1
      RAF_WEIGHT: 1.0
    RAF:
      KERNEL_SIZE: 3
      DOWN_SAMPLE_RATIO: 1
      CONV_DIM: 256
      NUM_CONV: 2
      LAST_DEFORM_ON: False
      SPLIT: True
      LOSS_TYPE: ("l1", "pos", "normal", 0)
RELATION:
  RELATION_ON: True
  USE_GT_BOX: False
  USE_GT_OBJECT_LABEL: False
INPUT:
  CROP:
    ENABLED: False
    SIZE: [ 0.8, 0.8 ]
  GT_SCALE_AWARE: True
  GT_REGRESSION_SCALE_AWARE: False
  CENTER_GAUSSIAN_IOU_MIN_OVERLAPS: [0.5, 0.5, 0.5]
  MIN_SIZE_TRAIN: (384, 512, 640, 768, 896,)
  MAX_SIZE_TRAIN: 1024
  MIN_SIZE_TEST: 640
  MAX_SIZE_TEST: 1024
SOLVER:
  IMS_PER_BATCH: 16 # linear scale these
  BASE_LR: 0.001 # linear scale these
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  STEPS: (40000,) # 12, 18, 20 epochs
  MAX_ITER: 90000 # 100000 # linear scale these
DATASETS:
  TEST: ("vg_minitest",)
OUTPUT_DIR: "./output/vg/fcsgg_hrnet_w48_trident_640x1024_ms"
