_BASE_: "FCSGG-Base.yaml"
MODEL:
  PIXEL_STD: [57.375, 57.120, 58.395] # pretrained coco resx101
  META_ARCHITECTURE: "CenterNet"
  WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x/139173657/model_final_68b088.pkl"
  BACKBONE:
    NAME: "build_resnet_fpn_p2_backbone"
    FREEZE_AT: 4
    FREEZE_ALL: False
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
    NORM: "SyncBN" # "SyncBN" "FrozenBN"
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  NECKS:
    ENABLED: False
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.002

OUTPUT_DIR: "./output/vg/fcsgg_resx101_32x8d_fpn_p2_608x1024"
