_BASE_: "FCSGG-Base.yaml"
MODEL:
  META_ARCHITECTURE: "CenterNet"
  WEIGHTS: ""
  BACKBONE:
    NAME: "build_hrnet_backbone"
  NECKS:
    ENABLED: False
  HEADS:
    NAME: CenternetCascadeHeads
    CONV_DIM: 64
    NUM_CONV: 4
    NORM: "SyncBN"
    NUM_CLASSES: 150
    IN_FEATURES: ["p1"]
    FREEZE: []#["cls_head", "wh_head", "reg_head"]
    RAF:
      KERNEL_SIZE: 3
      DILATION: 2
      LAST_DEFORM_ON: False
DATASETS:
  TRAIN: ("vg_train",)
#  VAL: ("vg_val",)
  TEST: ("vg_test",)
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  CLIP_GRADIENTS:
    ENABLED: True
  IMS_PER_BATCH: 24
  BASE_LR: 0.001
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 100
  STEPS: (40000, 80000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 5000
INPUT:
  GT_SCALE_AWARE: False
  MIN_SIZE_TRAIN: (256, 320, 384, 448, 512)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
RELATION:
  RELATION_ON: True
OUTPUT_DIR: "./output/vg/fcsgg_hrnet32_512x512_ms"
SEED: 2020
VERSION: 2
