_BASE_: "FCSGG-Base.yaml"
MODEL:
  SIZE_DIVISIBILITY: 64
  META_ARCHITECTURE: "CenterNet"
  HRNET:
    WEIGHTS: ""
    FINAL_STAGE_MULTISCALE: True
    NORM: "SyncBN"
    UPSAMPLE_MODE: "bilinear"
  BACKBONE:
    NAME: "build_hrnet_backbone"
  NECKS:
    ENABLED: True
    NAME: DualHRFPN
    IN_FEATURES: [ "hr2", "hr3", "hr4", "hr5" ]
    OUT_CHANNELS: [ 256 ]
    UPSAMPLE_MODE: "bilinear"
    NORM: "SyncBN"
    CONV_STRIDE: 1
    OUT_STRIDES: [ 4, 8, 16, 32 ]
    DEFORM_ON_PER_STAGE: [ False, False ]
  HEADS:
    NAME: MultiScaleSwitchNormDualHeads
    CONV_DIM: 128
    NUM_CONV: 4
    NORM: "SyncBN"
    IN_FEATURES: ["p2_0", "p3_0", "p4_0", "p5_0", "p2_1", "p3_1", "p4_1", "p5_1"]
    OUTPUT_STRIDES: [ 4, 8, 16, 32 ]
    LOSS:
      WH_WEIGHT: 0.1
    RAF:
      DOWN_SAMPLE_RATIO: 1
      CONV_DIM: 256
      NUM_CONV: 4
      SPLIT: True
      LOSS_TYPE: ("l1", "all", "normal", 10)
RELATION:
  RELATION_ON: True
INPUT:
  GT_SCALE_AWARE: True
  GT_REGRESSION_SCALE_AWARE: False
  USE_FIX_SIZE: True
  CENTER_GAUSSIAN_IOU_MIN_OVERLAPS: [0.5, 0.5, 0.5, 0.5]
SOLVER:
  IMS_PER_BATCH: 36
  BASE_LR: 0.001 # linear scale these
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 100
  STEPS: (40000,) # linear scale these
  MAX_ITER: 90000 # linear scale these
DATASETS:
  TEST: ("vg_minitest",)
OUTPUT_DIR: "./output/vg/fcsgg_hrnet_w32_dualhrfpn_4s_512x512_ms"
