MODEL:
  META_ARCHITECTURE: "CenterNet"
  WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
    FREEZE_AT: -1
    FREEZE_ALL: False
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "SyncBN" # "SyncBN" "FrozenBN"
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  NECKS:
    ENABLED: True
    NAME: FPNUpSampleNeck
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NORM: "SyncBN"
    FREEZE: False
  HEADS:
    NAME: CenternetMultiStageHeads
    CONV_DIM: 256
    NUM_CONV: 2
    NUM_STAGES: 2
    NORM: "SyncBN"
    FREEZE: [] #["cls_head_0", "cls_head_1", "wh_head", "reg_head"]
    RAF:
      LAST_DEFORM_ON: True
    NUM_CLASSES: 150
    IN_FEATURES: ["fpn_fused"]
    LOSS:
      HEATMAP_LOSS_TYPE: "efficient_focal_loss"
      WH_WEIGHT: 0.1
      RAF_WEIGHT: 0.1
DATASETS:
  TRAIN: ("vg_train",)
#  VAL: ("vg_val",)
  TEST: ("vg_test",)
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  CLIP_GRADIENTS:
    ENABLED: True
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 0
  STEPS: (40000, 70000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 5000
INPUT:
  MIN_SIZE_TRAIN: (256, 320, 384, 448, 512)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 384
  MAX_SIZE_TEST: 512
RELATION:
  RELATION_ON: True
OUTPUT_DIR: "./output/vg/fcsgg_res50fpn_fpnupsample_multistage_deform_256x512_ms"
SEED: 2020
VERSION: 2
