MODEL:
  META_ARCHITECTURE: "CenterNet"
  WEIGHTS: ""
  BACKBONE:
    NAME: "build_hrnet_backbone"
  NECKS:
    ENABLED: False
  HEADS:
    NAME: CenternetMultiStageHeads
    NUM_STAGES: 2
    NORM: "SyncBN"
    RAF:
      LAST_DEFORM_ON: True
    NUM_CLASSES: 150
    IN_FEATURES: ["p1"]
    FREEZE: []#["cls_head", "wh_head", "reg_head"]
    LOSS:
      HEATMAP_LOSS_TYPE: "efficient_focal_loss"
      WH_WEIGHT: 0.1
DATASETS:
  TRAIN: ("vg_train",)
#  VAL: ("vg_val",)
  TEST: ("vg_test",)
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  CLIP_GRADIENTS:
    ENABLED: True
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  WARMUP_FACTOR: 0.002
  WARMUP_ITERS: 500
  STEPS: (40000, 80000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 5000
INPUT:
  MIN_SIZE_TRAIN: (256, 320, 384, 448, 512)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 256
  MAX_SIZE_TEST: 512
RELATION:
  RELATION_ON: True
OUTPUT_DIR: "./output/vg/fcsgg_hrnet32_multistage_deform_256x512_ms"
SEED: 2020
VERSION: 2
